### ISSUE TITLE
Add padding to banner using media queries at 900px width

### ISSUE THREAD

**Issue by vickywane** [SaraVieira/blender-resources#18]
The banner ( topmost section ) of the landing page needs some padding when it's at a `900px` display ratio before it changes to a column view at `750px` width.

An image of this is attached below:
![Screenshot from 2020-12-11 20-34-07](https://user-images.githubusercontent.com/29664439/101979791-68572280-3c60-11eb-9470-5358ef04c21c.png)

**Comment by vickywane** [comment]
@SaraVieira I'll submit a PR to fix this in a few hours.

**Comment by vickywane** [comment]
@SaraVieira i just saw your commit [here](https://github.com/SaraVieira/blender-resources/commit/e6c2043402fa46fe1ce03fb5fd33bef8a0627fde). Issue still persists tho.

**Comment by SaraVieira** [comment]
Hey

My fix was for tablets, realized it was also broken in tablets :/
